export const allCharactersData = {
  data: [
    {
      id: 2,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
    },
    {
      id: 18,
      name: "Antenna Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/18.jpeg",
    },
    {
      id: 27,
      name: "Artist Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/27.jpeg",
    },
    {
      id: 77,
      name: "Cowboy Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/77.jpeg",
    },
    {
      id: 84,
      name: "Cult Leader Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/84.jpeg",
    },
    {
      id: 85,
      name: "Cyclops Morty",
      status: "Alive",
      species: "Humanoid",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/85.jpeg",
    },
    {
      id: 118,
      name: "Evil Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/118.jpeg",
    },
    {
      id: 123,
      name: "Fat Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/123.jpeg",
    },
    {
      id: 143,
      name: "Glasses Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/143.jpeg",
    },
    {
      id: 206,
      name: "Lizard Morty",
      status: "Alive",
      species: "Humanoid",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/206.jpeg",
    },
    {
      id: 229,
      name: "Morty Mart Manager Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/229.jpeg",
    },
    {
      id: 230,
      name: "Morty Jr.",
      status: "Alive",
      species: "Humanoid",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/230.jpeg",
    },
    {
      id: 232,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/232.jpeg",
    },
    {
      id: 233,
      name: "Morty K-22",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/233.jpeg",
    },
    {
      id: 366,
      name: "Trunk Morty",
      status: "Alive",
      species: "Humanoid",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/366.jpeg",
    },
    {
      id: 392,
      name: "Bearded Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/392.jpeg",
    },
    {
      id: 401,
      name: "Morty Jr's interviewer",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/401.jpeg",
    },
    {
      id: 473,
      name: "Bartender Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/473.jpeg",
    },
    {
      id: 474,
      name: "Dancer Cowboy Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/474.jpeg",
    },
    {
      id: 475,
      name: "Dancer Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/475.jpeg",
    },
    {
      id: 476,
      name: "Flower Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/476.jpeg",
    },
    {
      id: 480,
      name: "Purple Morty",
      status: "Alive",
      species: "Alien",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/480.jpeg",
    },
    {
      id: 505,
      name: "Fascist Shrimp Morty",
      status: "Alive",
      species: "Animal",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/505.jpeg",
    },
    {
      id: 512,
      name: "Morty’s Lawyer",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/512.jpeg",
    },
    {
      id: 518,
      name: "Wasp Morty",
      status: "Alive",
      species: "Animal",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/518.jpeg",
    },
    {
      id: 630,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/630.jpeg",
    },
    {
      id: 636,
      name: "Evil Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/636.jpeg",
    },
    {
      id: 637,
      name: "Morty’s Disguise",
      status: "Alive",
      species: "Human",
      gender: "Female",
      avatar: "https://rickandmortyapi.com/api/character/avatar/637.jpeg",
    },
    {
      id: 659,
      name: "Morty’s Father-in-law",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/659.jpeg",
    },
    {
      id: 660,
      name: "Morty’s Mother-in-law",
      status: "Alive",
      species: "Human",
      gender: "Female",
      avatar: "https://rickandmortyapi.com/api/character/avatar/660.jpeg",
    },
    {
      id: 661,
      name: "Morty’s Girlfriend",
      status: "Alive",
      species: "Human",
      gender: "Female",
      avatar: "https://rickandmortyapi.com/api/character/avatar/661.jpeg",
    },
    {
      id: 685,
      name: "Evolved Narnian Disguised as Morty",
      status: "Alive",
      species: "Humanoid",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/685.jpeg",
    },
    {
      id: 759,
      name: "Turkey Morty",
      status: "Alive",
      species: "Animal",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/759.jpeg",
    },
    {
      id: 805,
      name: "Baby Mouse Skin Morty",
      status: "Alive",
      species: "Human",
      gender: "Male",
      avatar: "https://rickandmortyapi.com/api/character/avatar/805.jpeg",
    },
  ],
};
